#!/usr/bin/env node

/**
 * Automatic Version Bumper
 * Increments patch version on every build
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const packageJsonPath = join(process.cwd(), 'package.json');

try {
  // Read package.json
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
  
  // Parse current version
  const [major, minor, patch] = packageJson.version.split('.').map(Number);
  
  // Determine bump type from environment or default to patch
  const bumpType = process.env.VERSION_BUMP || process.argv[2] || 'patch';
  
  let newVersion;
  switch (bumpType) {
    case 'major':
      newVersion = `${major + 1}.0.0`;
      break;
    case 'minor':
      newVersion = `${major}.${minor + 1}.0`;
      break;
    case 'patch':
    default:
      newVersion = `${major}.${minor}.${patch + 1}`;
      break;
  }
  
  // Update version
  packageJson.version = newVersion;
  
  // Write back to package.json
  writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
  
  console.log(`✅ Version bumped: ${major}.${minor}.${patch} → ${newVersion}`);
  
  // Write version to a file for use in the app
  const versionFilePath = join(process.cwd(), 'src', 'version.ts');
  const versionFileContent = `// Auto-generated by version bump script
export const APP_VERSION = '${newVersion}';
export const BUILD_DATE = '${new Date().toISOString()}';
`;
  writeFileSync(versionFilePath, versionFileContent);
  
  console.log(`✅ Version file updated: src/version.ts`);
  
} catch (error) {
  console.error('❌ Error bumping version:', error.message);
  process.exit(1);
}
